[package]
name = "accesskit_android"
version = "0.5.0"
authors.workspace = true
license.workspace = true
description = "AccessKit UI accessibility infrastructure: Android adapter"
categories.workspace = true
keywords = ["gui", "ui", "accessibility"]
repository.workspace = true
readme = "README.md"
edition.workspace = true
rust-version.workspace = true

[features]
embedded-dex = []

[dependencies]
accesskit = { version = "0.22.0", path = "../../common" }
accesskit_consumer = { version = "0.32.0", path = "../../consumer" }
jni = "0.21.1"
log = "0.4.17"

