[package]
name = "accesskit_unix"
version = "0.14.0"
authors.workspace = true
license.workspace = true
description = "AccessKit UI accessibility infrastructure: Linux adapter"
categories.workspace = true
keywords = ["gui", "ui", "accessibility"]
repository.workspace = true
readme = "README.md"
edition.workspace = true
rust-version.workspace = true

[features]
default = ["async-io"]
async-io = ["dep:async-channel", "dep:async-executor", "dep:async-task", "dep:futures-util"]
tokio = ["dep:tokio", "dep:tokio-stream"]

[dependencies]
accesskit = { version = "0.18.0", path = "../../common" }
accesskit_atspi_common = { version = "0.11.0", path = "../atspi-common" }
atspi = { version = "0.25", default-features = false, features = ["async-std"] }
futures-lite = "2.3"
serde = "1.0"
zbus = { version = "5.5", default-features = false, features = ["async-io"] }

# async-io support
async-channel = { version = "2.1.1", optional = true }
async-executor = { version = "1.5.0", optional = true }
async-task = { version = "4.3.0", optional = true }
futures-util = { version = "0.3.27", optional = true }

# tokio support
tokio-stream = { version = "0.1.14", optional = true }
[dependencies.tokio]
version = "1.32.0"
optional = true
features = ["macros", "net", "rt", "sync", "time"]

