[package]
name = "accesskit_adapter"
version = "0.29.2"
authors.workspace = true
license = "Apache-2.0"
description = "AccessKit UI accessibility infrastructure: cross-platform adapter"
categories.workspace = true
keywords = ["gui", "ui", "accessibility"]
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = ["accesskit_unix", "async-io"]
async-io = ["accesskit_unix/async-io"]
tokio = ["accesskit_unix/tokio"]

[dependencies]
accesskit = { version = "0.22", path = "../../common" }
winit-core = { version = "0.31.0-beta.2", default-features = false }
raw-window-handle = { version = "0.6.2", features = ["std"] }

[target.'cfg(target_os = "windows")'.dependencies]
accesskit_windows = { version = "0.30.0", path = "../windows" }

[target.'cfg(target_os = "macos")'.dependencies]
accesskit_macos = { version = "0.23.0", path = "../macos" }

[target.'cfg(any(target_os = "linux", target_os = "dragonfly", target_os = "freebsd", target_os = "openbsd", target_os = "netbsd"))'.dependencies]
accesskit_unix = { version = "0.18.0", path = "../unix", optional = true, default-features = false }

[target.'cfg(target_os = "android")'.dependencies]
accesskit_android = { version = "0.5.0", path = "../android", optional = true, features = ["embedded-dex"] }
android-activity = { version = "0.6.0" }

