[package]
name = "accesskit_atspi_common"
version = "0.8.0"
authors.workspace = true
license.workspace = true
description = "AccessKit UI accessibility infrastructure: core AT-SPI translation layer"
categories.workspace = true
keywords = ["gui", "ui", "accessibility"]
repository.workspace = true
readme = "README.md"
edition.workspace = true
rust-version.workspace = true

[features]
simplified-api = []

[dependencies]
accesskit = { version = "0.15.0", path = "../../common" }
accesskit_consumer = { version = "0.23.0", path = "../../consumer" }
atspi-common = { version = "0.3.0", default-features = false }
serde = "1.0"
thiserror = "1.0.39"
zvariant = { version = "3", default-features = false }

