[package]
name = "accesskit_multitree"
version = "0.1.0"
authors.workspace = true
license = "Apache-2.0"
description = "AccessKit UI accessibility infrastructure: multitree adapter"
categories.workspace = true
keywords = ["gui", "ui", "accessibility", "winit"]
repository.workspace = true
readme = "README.md"
edition.workspace = true
rust-version.workspace = true

[dependencies]
accesskit = { version = "0.21.1", path = "../../common" }
