[package]
name = "accesskit_multi_tree"
version = "0.1.0"
edition = "2024"

[dependencies]
accesskit = { version = "0.21.1", path = "../common" }
accesskit_winit = { version = "0.29.1", path = "../platforms/winit" }
